### ISSUE TITLE
Adding "Etag" header

### ISSUE THREAD

**Issue by wysow** [middlewares/cache#2]
Hello,

First, thank you for this middleware collection!

I'm wondering if, as stated on https://github.com/micheh/psr7-cache/blob/master/src/CacheUtil.php#L118-L121, it is a good idea to add the `ETag` header when we are returning some cached response?

What do you think? I can try to do a PR if you think it's a good idea.

**Comment by oscarotero** [comment]
I'm not sure about what do you mean.
In theory, if you're returning the ETag header, the middleware returns it too, because it returns the same headers of the cached response: https://github.com/middlewares/cache/blob/master/src/Cache.php#L48

**Comment by wysow** [comment]
No that's not what I meant, I was wondering if it sounds right to ALSO add the `Etag` header when we are adding the `Last-Modified` one in https://github.com/middlewares/cache/blob/master/src/Cache.php#L62. 

It seems that the 2 headers should be added when caching is enabled, as per the docblock linked in my first comment.

**Comment by oscarotero** [comment]
My idea was the inner middleware (the route controller) returns a response with the ETag (if it's needed), because this is something specific to the current route. Because the response headers is saved in cache, and the method `isNotModified` can handle the ETag header of the request/cached response: https://github.com/micheh/psr7-cache/blob/master/src/CacheUtil.php#L264, I don't know why add an ETag header automatically.

Anyway, if you are convinced and want to do a PR to illustrate the idea, feel free.
Thank you

**Comment by wysow** [comment]
OK got it, I didn't see this in `CacheUtil` at first, so let's keep it like this, closing this now.
